# Generated by Django 3.2.4 on 2022-12-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_choice_guest_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.CharField(blank=True, max_length=2096, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_image',
            field=models.CharField(blank=True, max_length=2096, null=True),
        ),
    ]
